[database]
# データベースのURLを指定してエンジンを作成
url = "sqlite:///kmsearch.sqlite"

[explore]
# units = ["file", "page", "word"]
units = ["page"]

[explore.pdf]
extensions = [".pdf"]

[explore.pdf.ocr]
enabled = true
minSize = 1_000
maxSize = 1_000_000_000

[explore.pdf.text]
enabled = true
minSize = 1_000
maxSize = 1_000_000_000

[explore.image]
extensions = [
    ".avif", ".webp", ".tif", ".tiff",
    ".jpg", ".jpeg", ".bmp", ".png",
]
[explore.image.ocr]
enabled = true
minSize = 1_000
maxSize = 1_000_000_000
[explore.excel]
extensions = [ ".xlsx", ".xlsm", ]

[explore.excel.cell]
enabled = true
minSize = 1_000
maxSize = 1_000_000

[explore.excel.sharp]
enabled = true
minSize = 1_000
maxSize = 1_000_000

[common]
[common.ocr]
languages = ["en"]
systemLanguage = true
modelPath = ""
minWordLength = 3
minConfident  = 0.4

[common.image]
maxImagePixels = 1_115_817_600
